---
- name: Configure Elasticsearch Hosts
  hosts: elastic
  become: True
  tags: elasticsearch
  tasks:
    - name: run "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: add Elasticsearch's official GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: save the repository definition to /etc/apt/sources.list.d/elastic-7.x.list
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: elastic-7.x.list

    - name: install Elasticsearch 
      apt:
        name: elasticsearch
        update_cache: yes

    - name: modify /etc/elasticsearch/elasticsearch.yml
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: "{{ item }}"
        create: yes
      with_items:
        - "cluster.name: my_cluster"
        - "network.host: {{ hostvars[inventory_hostname].ansible_enp0s8.ipv4.address }}"
        - "discovery.seed_hosts: [\"192.168.34.11\", \"192.168.34.12\", \"192.168.34.13\"]"
        - "cluster.initial_master_nodes: [\"192.168.34.11\", \"192.168.34.12\", \"192.168.34.13\"]"

    - name: modify /etc/elasticsearch/jvm.options Xms2g
      shell: "sed -i 's/Xms1g/Xms2g/' /etc/elasticsearch/jvm.options"

    - name: modify /etc/elasticsearch/jvm.options Xmx2g
      shell: "sed -i 's/Xmx1g/Xmx2g/' /etc/elasticsearch/jvm.options"
    
    - name: enable elasticsearch service and make sure the service is runnning
      systemd:
        name: elasticsearch.service
        enabled: yes
        state: started
        daemon_reload: yes

- name: Configure Kibana Host
  hosts: kibana
  become: True
  tags: kibana
  tasks:
    - name: run "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: add Elasticsearch's official GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: save the repository definition to /etc/apt/sources.list.d/elastic-7.x.list
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: elastic-7.x.list

    - name: install Kibana 
      apt:
        name: kibana
        update_cache: yes

    - name: modify /etc/kibana/kibana.yml
      lineinfile:
        path: /etc/kibana/kibana.yml
        line: "{{ item }}"
        create: yes
      with_items:
        - "server.host: \"{{ hostvars[inventory_hostname].ansible_enp0s8.ipv4.address }}\""
        - "elasticsearch.hosts:"
        - "  - \"http://192.168.34.11:9200\""
        - "  - \"http://192.168.34.12:9200\""
        - "  - \"http://192.168.34.13:9200\""

    - name: enable kibana service and make sure the service is runnning
      systemd:
        name: kibana.service
        enabled: yes
        state: started
